apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-api
  namespace: mc-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mc-api
  template:
    metadata:
      labels:
        app: mc-api
    spec:
      containers:
      - name: mc-api
        image: omkar8284/mc-api:phase4          # <-- your updated CPU-burn version
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

        # CPU requests/limits required for autoscaling
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"

        # -------- PROBE FIXES BELOW --------
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 5

        env:
        - name: NODE_NAME
          valueFrom:
            fieldR
