apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mc-api-ingress
  namespace: mc-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: mc-api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mc-api-svc
            port:
              number: 8080
