apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mc-api-keda
  namespace: mc-namespace
spec:
  scaleTargetRef:
    name: mc-api
  minReplicaCount: 2
  maxReplicaCount: 10

  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "60"

